- CHANGELOG.md
- node/resolvers/index.ts
- node/service.json
- `/b2b/oms/user/checkout/` route to return `paymentTerms` and Cost Center addresses
[Workspace](https://b2bcheckout--sandboxusdev.myvtex.com/b2b/oms/user/checkout/)
> [B2BCHCKOUT-6 and B2BORG-36] Added checkout route

- CHANGELOG.md
- graphql/schema.graphql
- node/mdSchema.ts
- node/resolvers/index.ts
- node/typings.d.ts
Provides GraphQL interface to get and set payment terms for each cost center
Linked here: https://quotes--sandboxusdev.myvtex.com
> [B2BORG-18] Support payment terms for cost centers

- CHANGELOG.md
- graphql/schema.graphql
- node/package.json
- node/resolvers/index.ts
- node/yarn.lock
Currently, based on https://github.com/vtex-apps/b2b-organizations-graphql/blob/master/graphql/schema.graphql, if a cost center has multiple addresses and you only need to update one, you’ll have to push all of them into a cost center via updateCostCenter , instead of being able to target just the one that needs edited
There is no simple way to add a new address to an existing cost center which already has address(es) assigned to it.
So to solving those issues I've created 2 mutations to create and update the cost center address:
```graphql
createCostCenterAddress(
costCenterId: ID
address: AddressInput
): MutationResponse @withSession @withPermissions
updateCostCenterAddress(
costCenterId: ID
address: AddressInput
): MutationResponse @withSession @withPermissions
```
This solution is on …
> [B2BORG-78] API mutation to support updating a single cost center address

- .github/workflows/cypress.yml
Just adding Cypress tests to run in a daily basis.
> ADD Run Cypress on a schedule basis

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/Mutations/CostCenters.ts
- node/resolvers/Mutations/Organizations.ts
Added duplicate check for creating organization request
[b2borg--sandboxusdev.myvtex.com/_v/private/vtex.b2b-organizations-graphql@0.16.0/graphiql/v1](url)
`mutation {
createOrganizationRequest(
input: {
name: "Aurorayeah",
b2bCustomerAdmin: {
firstName: "Aurora",
lastName: "Shen",
email: "aurora.shen@vtex.com.br"
}
defaultCostCenter: {
name: "wowo",
address: {
postalCode: "07302",
country: "U.S",
city: "Jersey City",
state: "New Jersey",
street: "My Home",
number: "11",
} 
businessDocument: "right"
}
}
)
{
id
href
status
}
}
`
> [B2BORG-96] Fix duplicate check

- cy-runner.yml
> Added multi Organization testcases

- .github/workflows/qe-pull-request.yml
Add types for pull request events.
> fix: Add types for pull resquest

- cy-runner.yml
Enable User Impersonation Feature & Updated cy-runner strategy
> Run user impersonation tests in cypress E2E

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/catalog.ts
- node/clients/index.ts
- node/resolvers/Mutations/Settings.ts
- node/resolvers/Queries/Users.ts
What problem is this solving?
Added a Setting table for binding settings.
The binding will check user permission to show the "My Organization" Table in profile
How to test it?
[Profile](https://aurora142--b2bstoreqa.myvtex.com/account#/profile)
[Admin Setting](https://aurora142--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations/#/settings)
[graphql](https://aurora142--b2bstoreqa.myvtex.com/_v/private/vtex.b2b-organizations-graphql@0.19.6/graphiql/v1?query=query%20getBinding(%24email%3A%20String!)%20%7B%0A%20%20getBinding(email%3A%20%24email)%20%0A%7D&operationName=getBinding&variables=%7B%0A%20%20%22email%22%3A%22aurora.shen%40vtex.com.br%22%0A%7D)
> [B2BORG-142] Set Bindings

- CHANGELOG.md
- manifest.json
Hotfix, app doesn't have permission to save app Settings
> Add permission to save app settings

- CHANGELOG.md
- graphql/schema.graphql
- node/mdSchema.ts
- node/resolvers/Mutations/Organizations.ts
- Added the salesChannel field to Organization type
- Added the salesChannel field the updateOrganization mutation
[Workspace](https://aurora--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations#/organizations)
> [B2BORG-144] sales channel tab

- CHANGELOG.md
- node/resolvers/Mutations/Settings.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/config.ts
This PR changes the app setting to store in vBase
[Workspace](https://aurora--b2bstoreqa.myvtex.com)
[GraphiQL](https://aurora--b2bstoreqa.myvtex.com/_v/private/vtex.b2b-organizations-graphql@0.19.6/graphiql/v1?query=query%20getAppSettings%20%7B%0A%20%20getAppSettings%7B%0A%20%20%20%20adminSetup%0A%20%20%7D%0A%7D&operationName=getAppSettings)
> [B2BORG-153] change settings to vBase

- .github/workflows/qe-dispatch.yml
- .github/workflows/qe-pull-request-target.yml
- .github/workflows/qe-pull-request.yml
- .github/workflows/qe-push.yml
- .github/workflows/qe-schedule.yml
- CHANGELOG.md
- graphql/schema.graphql
- node/clients/catalog.ts
- node/clients/payments.ts
- node/resolvers/Mutations/CostCenters.ts
- node/resolvers/Mutations/Organizations.test.ts
- node/resolvers/Mutations/Organizations.ts
- node/resolvers/Mutations/Users.ts
- node/resolvers/Queries/CostCenters.ts
- node/typings.d.ts
This PR allows creation of orgs providing only a list with the names of `paymentTerms`, `collections` and `sellers`.
The creation process will get the `paymentTerms`, `collections` and `sellers` configured for the merchant and check if the provided name exists and retrieve the id before inserting the new org on Master Data.
Here is an example of the creation of a org with these parameters and the result after inserting it
Creation
```
mutation Org ($input: NormalizedOrganizationInput!) {
createOrganizationAndCostCentersWithId(input: $input) {
status,
href
id
}
}
{
"input": {
"id": "B2BTEAM1394-4",
"name": "B2BTEAM1394-4",
"b2bCustomerAdmin": {
"firstName": "Enzo",
"lastName": "Mercanti",
"email": "enzo.mercanti@vtex.com.br"
},
"priceTables": [
"platinum",
"gold"
],
"paymentTerms": [ …
```
> feat: fetch fields info on org creation

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/storefrontPermissions.ts
- node/queries/getUsersByEmail.ts
- node/resolvers/Mutations/Users.ts
- Add new removeUserWithEmail graphql API for bulk import use case
> feat: Add new removeUserWithEmail graphql API for bulk import use case

- CHANGELOG.md
- node/clients/storefrontPermissions.ts
Provide correct tokens to clients. More info: https://vtex-dev.atlassian.net/browse/B2BTEAM-1633
> fix: provide correct tokens to clients

- CHANGELOG.md
- node/resolvers/directives/checkAdminAccess.ts
- node/resolvers/directives/checkUserAccess.ts
- node/resolvers/directives/helper.ts
Fix check access directives by allowing appkey tokens for authentication
> fix: check access directive

- CHANGELOG.md
- manifest.json
- node/events/appAllEvents.ts
- node/events/appDependenciesUpdatedEvent.ts
- node/events/kubeRouterAuditEvent.ts
- node/index.ts
- node/mdSchema.ts
- node/resolvers/Queries/Organizations.ts
- node/resolvers/config.ts
- node/service.json
- node/yarn.lock
SBD utilizes the trade name for the name of the company and the name as their internal ID. This change allows you to search by both fields.
Also implements an auto-update 
[Workspace](https://wender--sbdstoruat.myvtex.com/admin/b2b-organizations/organizations/#/organizations)
> Added Trade Name to Organizations Listing Page

- CHANGELOG.md
- graphql/schema.graphql
- node/clients/LMClient.ts
- node/clients/index.ts
- node/package.json
- node/resolvers/directives/auditAccess.ts
- node/resolvers/directives/checkAdminAccess.ts
- node/resolvers/directives/checkUserAccess.ts
- node/resolvers/directives/helper.ts
- node/utils/metrics/auth.ts
- node/yarn.lock
* Add audit metrics to some graphql APIs
* Add license manager client (copied from `storefront-permissions`)
* Improve logging and access control
More info: https://vtex-dev.atlassian.net/browse/B2BTEAM-1746
> fix: update admin token validation and add audit metric

- CHANGELOG.md
- graphql/directives.graphql
- graphql/schema.graphql
- node/resolvers/directives.ts
- node/resolvers/directives/validateAdminUserAccess.ts
- node/utils/metrics/auth.ts
Add new admin user token validation directive.
More info: https://vtex-dev.atlassian.net/browse/B2BTEAM-1750
> fix: add admin user token validation directive

- CHANGELOG.md
- node/resolvers/directives/helper.ts
Add more logs to store token validation. More info on [https://vtex-dev.atlassian.net/browse/B2BTEAM-1800](https://vtex-dev.atlassian.net/browse/B2BTEAM-1800)
> fix: add logging for store token validation

- CHANGELOG.md
- graphql/schema.graphql
Add new admin token validation directive to some APIs. For more information, see: https://vtex-dev.atlassian.net/browse/B2BTEAM-1832
> fix: add new admin token validation directive to some APIs

- CHANGELOG.md
- graphql/schema.graphql
- manifest.json
- node/package.json
- node/resolvers/directives.ts
- node/resolvers/directives/checkAdminAccess.ts
- node/resolvers/directives/checkUserAccess.ts
Revert commits from v.1.0.0 release.
This was done as b2b suite app major upgrades are a bit more complex than expected and will be postponed for a few weeks.
Latest available release of this app is v0.65.0
> Revert "Release v1.0.0"
