CHANGELOG.md, node/clients/graphqlServer.ts, node/index.ts, node/resolvers/index.ts
Previous PR neglected to initialize the field resolvers for the B2BUser GraphQL type. This PR enables the query to return the organization name, cost center name, and role details.
GraphiQL: https://quotes--sandboxusdev.myvtex.com/_v/private/vtex.b2b-organizations-graphql@0.2.3/graphiql/v1?query=query%20%7B%0A%20%20getUsers(organizationId%3A%20%223394da75-3694-11ec-82ac-0e63d6323601%22)%20%7B%0A%20%20%20%20email%0A%20%20%20%20orgId%0A%20%20%20%20organizationName%0A%20%20%20%20costCenterName%0A%20%20%20%20role%20%7B%0A%20%20%20%20%20%20slug%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
=> [B2BORG-34] Initialize field resolvers for B2BUser queries

CHANGELOG.md, graphql/schema.graphql, node/resolvers/index.ts
Removed permission checks from `getOrganizationById`, `getCostCentersByOrganizationId`, `getCostCenterById` queries and created new (additional) storefront queries that return the same data but only if the user has the correct permissions.
GraphiQL: https://quotes--sandboxusdev.myvtex.com/_v/private/vtex.b2b-organizations-graphql@0.3.1/graphiql/v1?query=query%20%7B%0A%20%20getOrganizationById(id%3A%20%223394da75-3694-11ec-82ac-0e63d6323601%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20costCenters%0A%20%20%20%20collections%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
=> Create new storefront queries

CHANGELOG.md, node/mdSchema.ts, node/resolvers/index.ts
Enables newly created organizations, organization requests, cost centers, and changes to any of the above to be immediately visible in their respective UIs.
Also deprecates the `costCenters` array in each organization data entity as this is unnecessary. Instead, to get an organization's cost centers, apps can use the `getCostCentersByOrganizationId` query.
Linked in https://quotes--sandboxusdev.myvtex.com
=> [B2BORG=42] Enable MD immediate indexing and deprecate field

CHANGELOG.md, manifest.json, node/assets/organizationStatusChange.html, node/clients/email.ts, node/index.ts, node/resolvers/index.ts, node/resolvers/message.ts, node/service.json, node/templates/index.ts, node/templates/organizationStatusChanged.ts
Adds a new email template for organization status changes. When an organization's status is changed, any `customer-admin`s assigned to the organization will be notified. 
Also, previous version relied on AppSettings to store data about MD schemas. Dependency apps can't have app settings, so this logic has been removed and replaced with VBASE. This will allow the app to function properly without being explicitly installed in a workspace.
Linked in https://quotes--sandboxusdev.myvtex.com
Assign yourself as a customer-admin of an organization and then change the organization's status. You should receive an email.
=> [B2BORG-19] Send email when org status changes, remove app settings

CHANGELOG.md, graphql/schema.graphql, node/resolvers/index.ts
This PR fixes two main bugs reported by the BitCot QA team:
- organization admin was previously unable to edit or remove users in their organization
- searching for organizations, cost centers, or organization requests with spaces in their names was not possible
The solution to the first issue was to make sure the user's CL ID is being passed to the mutation. There will be a related PR opened in `vtex.b2b-organizations` to address the frontend side of this as well.
The solution to the second issue was to surround the search term in quotes when constructing the `where` clause for Masterdata.
App is currently linked in https://quotes--sandboxusdev.myvtex.com
=> [B2BORG-45] Fix GraphQL bugs

CHANGELOG.md, node/clients/storefrontPermissions.ts, node/constants.ts, node/resolvers/index.ts
Our team recently decided that when assigning payment terms to an organization, any of the store's payment methods should be eligible for assignment. Until now, we have only been allowing Promissory payment types to be assigned. This PR alters the getPaymentTerms query so that all enabled payment methods are available for assignment.
For credit cards (Visa, Mastercard, etc), the app filters these out of the list and adds a generic "Credit card" entry to the array instead. This is because all credit cards in checkout are combined into a single "Credit card" option.
This PR also fixes an unrelated bug where the wrong app's permissions were being checked in the orders route handler. We need to check the user's permissions for vtex.b2b-orders-history and not their permissions for …
=> [B2BORG-83] Allow all payment methods to be assigned to orgs

CHANGELOG.md, graphql/schema.graphql, node/mdSchema.ts, node/package.json, node/resolvers/index.ts, node/typings.d.ts, node/yarn.lock
Update MD schema and GraphQL schema/resolvers to support an optional `businessDocument` string field within the cost center data model. This field will be used for Brazilian companies to store their CNPJ for each cost center. This PR also allows the `businessDocument` for the default cost center to be specified when an organization request is submitted.
Linked here: https://b2bsuite--sandboxusdev.myvtex.com
Use GraphiQL to get a cost center by ID, example:
https://b2bsuite--sandboxusdev.myvtex.com/admin/graphql-ide
```
query {
getCostCenterById(id: "74bc8b61-94ed-11ec-835d-02e7a56b8989") {
name
organization
businessDocument
}
}
```
or change the businessDocument like so:
```
mutation {
updateCostCenter(id: "74bc8b61-94ed-11ec-835d-02e7a56b8989", input: { name: "Cost Center 3", …
```
=> [B2BORG-84] Add businessDocument to cost center data model

CHANGELOG.md, node/mdSchema.ts, node/resolvers/index.ts
What problem is this solving?
add subfield `email` of the `b2bCustomerAdmin` field to check duplicate requests by email
How to test it?
test at [https://aurora--sandboxusdev.myvtex.com/_v/private/vtex.b2b-organizations@1.2.2/graphiql/v1](url) 
example :
`query {
getOrganizationRequests(
status: ["pending", "approved"],
search: "aurora.shen@vtex.com.br",
page: 1,
pageSize: 25,
sortOrder: "DESC",
sortedBy: "created"){
data {
b2bCustomerAdmin {
firstName
lastName
email
}
}
}
}`
=> [B2BORG-82] Check duplicate requests

CHANGELOG.md, manifest.json, node/clients/Oms.ts, node/clients/checkout.ts, node/clients/index.ts, node/package.json, node/resolvers/Routes/index.ts, node/service.json, node/yarn.lock
Adds a permission check to the app's `order` route to ensure that the frontend user has permission to view the order in question. Also the app now uses the admin version of the OMS API to get the order details, because this API returns the shopper's actual email inside the `clientProfileData` object, instead of a masked version. We need this email to check in `b2b-order-history` if the current user was the one who placed the order.
Also adds a new route for order cancellation requests since normally the frontend user is only able to request the cancellation of an order that they personally placed. This route uses the app's credential (and the `CancelaPedidos` policy) to submit the cancellation request using checkout's private API route, after first ensuring that the user has permissions …
=> [B2BORDERS-8] New route and permission checks for orders history

CHANGELOG.md, docs/README.md, graphql/schema.graphql, node/mdSchema.ts, node/resolvers/Mutations/CostCenters.ts, node/resolvers/Mutations/Organizations.ts, node/typings.d.ts
We have had a request to add `tradeName` and `phoneNumber` fields to our organization data structure, as these fields are requested in checkout. This PR lays the groundwork by updating the GraphQL schema and resolvers to accept and return these fields, as well as adding them to the Masterdata schema. 
https://b2bsuite--sandboxusdev.myvtex.com/_v/private/vtex.b2b-organizations-graphql@0.18.0/graphiql/v1
Run the following queries and mutations:
```
mutation {
createOrganizationRequest(input: {
name: "(some name)"
tradeName: "This is the Trade Name"
b2bCustomerAdmin: {
firstName: "(some name)"
lastName: "(some name)"
email: "(some unused email)"
}
defaultCostCenter: {
name: "Trade Name CC"
address: {
addressId: "123"
addressType: "residential"
addressQuery: null
postalCode: "14617"
country: …
```
=> [B2BORG-118] Add tradeName and phoneNumber fields

CHANGELOG.md, graphql/schema.graphql
Hotfix for previous PR: https://github.com/vtex-apps/b2b-organizations-graphql/pull/48
`tradeName` argument was missing from the `updateOrganization` mutation
Linked in https://b2bsuite--sandboxusdev.myvtex.com
=> [B2BORG-118] Update schema

CHANGELOG.md, node/resolvers/Mutations/CostCenters.ts, node/resolvers/Mutations/Organizations.ts, node/utils/GraphQLError.ts
If a user attempts to remove an organization's tradeName or a cost center's phoneNumber, the UI will report that the organization or cost center was saved successfully, but upon reloading the page, the previous value will still be present. 
This PR fixes this issue by allowing empty strings to be considered as "truthy" when updating the org or cost center. 
Linked here: https://b2bsuite--sandboxusdev.myvtex.com
=> [B2BORG-118] Allow empty string for tradeName and phoneNumber

CHANGELOG.md, node/resolvers/Queries/CostCenters.ts, node/typings.d.ts
A client imported many cost centers via API (not sure if it was through GraphQL or directly into MasterData) and neglected to assign `addressId`s to the cost center addresses. This caused problems with selecting addresses in checkout. To solve this problem, this PR adds logic to automatically generate and save a new `addressId` when a missing ID is detected. The app will do this whenever the `getCostCenterById` or `getCostCenterByIdStorefront` queries are used.
Go to https://hermespardini.myvtex.com/admin/graphql-ide and choose `vtex.b2b-organizations-graphql`
Use this query: 
```
query {
getCostCenterById(id: "3072226f-b445-11ec-835d-0acb4ec87a67") {
name
addresses {
addressId
state
postalCode
street
}
}
}
```
This should return an `addressId` of `null` (if it doesn't, find a new cost …
=> [B2BORG-147] Fix missing addressIds

CHANGELOG.md, node/resolvers/Queries/Users.ts
The default of the `getBinding` should be true if no channel selected
[Setting](https://auroratest--productusqa.myvtex.com/admin/b2b-organizations/organizations#/settings)
[graphql](https://aurora142--b2bstoreqa.myvtex.com/_v/private/vtex.b2b-organizations-graphql@0.19.6/graphiql/v1?query=query%20getBinding(%24email%3A%20String!)%20%7B%0A%20%20getBinding(email%3A%20%24email)%20%0A%7D&operationName=getBinding&variables=%7B%0A%20%20%22email%22%3A%22aurora.shen%40vtex.com.br%22%0A%7D)
=> bugfix binding default

CHANGELOG.md, node/mdSchema.ts, node/resolvers/Mutations/Organizations.ts, node/typings.d.ts
- When creating a new organization request, and the `auto approval` setting is enabled. The create Organization schema is not accepting any custom fields
- This can be tested [here](https://alberto--whitebird.myvtex.com/)
=> Update create Organization schema and request

CHANGELOG.md, node/clients/Oms.ts
The orders history page is not loading on the production domain of our stores. The call to /b2b/oms/users/orders fails with a 403. More details [here](https://vtex.slack.com/archives/C054PQH3GJF/p1685456760248619).
From my investigation, the store user token works with the failing call to the OMS API, and it's always present on the production domains, while auth token may be different. We also have other logic within b2b suite that gives precedence to the store user token vs auth token, probably for the same reason. So my fix here is the same: give precedence to the store user token, using it when present.
Unfortunately this is only really testable on a production domain. So we'll try installing this in a real account to validate the fix before publishing.
For now my test was to make sure …
=> Use the store user token for oms calls

.github/workflows/cabueta.yml, CHANGELOG.md
Add [Cabueta](https://github.com/vtex/cabueta) action to scan for vulnerabilities.
The idea is call graphql operations with examples using the platform [Nuclei](https://github.com/projectdiscovery/nuclei).
After the pull request merge, it will show the workflow to execute on [Actions](https://github.com/vtex-apps/b2b-organizations-graphql/actions)
=> chore: configure Cabueta to report vulnerabilities

.github/workflows/cabueta.yml, CHANGELOG.md
Scan the graphql endpoint to find vulnerabilities. 
The Cabueta referenced github action was in private account, changed to use public version.
=> fix: adjust Cabueta source and target url

.github/workflows/cabueta.yml, CHANGELOG.md
It was needed to add a implicit flag for not uploading Cabueta logs. 
When the flag isn't setting, the action failed.
=> fix: add a flag for not uploading Cabueta logs

CHANGELOG.md, node/service.json
This app's service routes lack the `/_v/private/` prefix, meaning that the user's session token will be stripped out by our CDN when the app is accessed via the final public domain. This results in users always encountering a 403 error and unable to view their B2B order history.
This PR adds the prefix to the routes, and a matching PR will be opened on B2B Orders History so that the frontend requests the correct new paths.
I did not change the "checkout" route, as I couldn't find any app that uses it.
=> Fix: allow service routes to access session token

CHANGELOG.md, node/clients/Oms.ts
The orders history page is not loading on the production domain of our stores. The call to /b2b/oms/users/orders fails with a 403. More details [here](https://vtex.slack.com/archives/C054PQH3GJF/p1689952463685259).
[https://shop.indola.es](https://shop.indola.es/account?workspace=ki849394#/orders-history)
[https://www.rivieraworks.ro](https://www.rivieraworks.ro/account?workspace=ki849394#/orders-history)
=> fix authentication when perform a GET Order

CHANGELOG.md, node/clients/Orders.ts, node/clients/index.ts, node/package.json, node/resolvers/Routes/index.ts, node/yarn.lock
Use Orders endpoint instead of OMS endpoint to obtain order information. The new Orders endpoint returns the correct orderGroup (unlike the OMS endpoint) and this orderGroup is used to generate a new order when clicking on the "Order Again" button.
Ultimately this PR is fixing the KI: "Order Again from B2B Orders History doesn't work".
1. Make an order
2. Go to "My Account" -> "Orders"
3. Click on "Order again" button for the order you just created. It should create a new cart with the same items.
[Workspace](https://b2bteam1187--b2bstoreqa.myvtex.com/account#/orders-history)
* https://github.com/vtex-apps/b2b-organizations-graphql/pull/124
=> Add Orders client and use it to get orders info

CHANGELOG.md, manifest.json, node/package.json, node/resolvers/Mutations/Users.ts, node/yarn.lock
Using Master Data V2, we don't have a trigger to run on "delete event" like in V1. This way we can't run scripts when deleting a user. Only on adding or updating. My motivation for this is to add the ability to run scripts after a delete action.
This modification will trigger an event sending a payload containing the is and email of the deleted user. 
With this, we can add an event listener and run scripts needed for that scenario
To test, link this branch to a workspace. Then from another app, listen to an event called `b2b-organizations-graphql.removeUser`
Like this: `service.json`
=> Add event trigger to deleteUser resolver

CHANGELOG.md, node/package.json, node/resolvers/Mutations/Organizations.ts, node/typings.d.ts, node/utils/metrics/metrics.ts, node/utils/metrics/organization.test.ts, node/utils/metrics/organization.ts, node/yarn.lock
We need to measure the B2B Suite product better to understand the behavior of merchants and buyer organizations. As described in [this doc](https://docs.google.com/document/d/1PdtmfL4rIKpzKUBR6ZGqqixMsfFzuqI38xmtSJ8wki8/edit).
- Access some organization in the workspace, path `admin/b2b-organizations/organizations`
- Change some data
- Use the query editor on Redshift to find the event persisted 1 hour after the changes
- Query
```SQL
select 
json_extract_path_text(json_serialize(payload), 'kind') as kind,
json_extract_path_text(json_serialize(payload), 'account') as account,
payload,
ingestion_time
FROM
vtex.schemaless.b2b_suite_buyerorg_data_raw b2b_raw
where account = 'b2bsuite'
and kind = 'update-organization-graphql-event'
``` …
=> feat: add metric on updating organization data

CHANGELOG.md, node/resolvers/Mutations/Users.ts, node/utils/metrics/metrics.ts, node/utils/metrics/organization.ts, node/utils/metrics/user.test.ts, node/utils/metrics/user.ts, sonar-project.properties
We need to measure the B2B Suite product better to understand the behavior of merchants and buyer organizations. As described in [this doc](https://docs.google.com/document/d/1PdtmfL4rIKpzKUBR6ZGqqixMsfFzuqI38xmtSJ8wki8/edit).
- Access some organization in the workspace, path `admin/b2b-organizations/organizations`
- Go to Users tab
- Add an user
- Update the same user
- Remove the user
- Query
```SQL
select 
json_extract_path_text(json_serialize(payload), 'kind') as kind,
json_extract_path_text(json_serialize(payload), 'account') as account,
payload,
ingestion_time
FROM
vtex.schemaless.b2b_suite_buyerorg_data_raw b2b_raw
where kind like '%user%'
and account = 'b2bsuite'
```
[Workspace](https://b2bteam1260--b2bsuite.myvtex.com/admin)
The merge for this PR depends of #127.
=> feat: buyer org users metrics

CHANGELOG.md, node/resolvers/Mutations/Organizations.ts, node/utils/metrics/impersonate.ts, node/utils/metrics/metrics.ts, node/utils/metrics/organization.test.ts, node/utils/metrics/organization.ts, node/utils/metrics/user.test.ts, node/utils/metrics/user.ts
We need to measure the B2B Suite product better to understand the behavior of merchants and buyer organizations. As described in [this doc](https://docs.google.com/document/d/1PdtmfL4rIKpzKUBR6ZGqqixMsfFzuqI38xmtSJ8wki8/edit).
- Access some organization request in the workspace, path `/admin/b2b-organizations/requests`
- Visualize an organization with status "Pending"
- Click in the button "Approve" or "Reject"
```SQL
select 
json_extract_path_text(json_serialize(payload), 'kind') as kind,
json_extract_path_text(json_serialize(payload), 'account') as account,
payload,
ingestion_time
FROM
vtex.schemaless.b2b_suite_buyerorg_data_raw b2b_raw
where kind  = 'change-organization-status-graphql-event'
and account = 'b2bsuite'
```
[Workspace](https://b2bteam1254--b2bsuite.myvtex.com/admin)
=> feat: approval and rejection metric

CHANGELOG.md, node/package.json, node/resolvers/Mutations/Users.test.ts, node/resolvers/Mutations/Users.ts, node/yarn.lock
The users with the `sales` roles can't impersonate users, even if they have permission.
- Open the path /account#/organization, log with sales role account
- Go to Users
- Click in the 3 points to impersonate the user.
[Workspace](https://www.rivieraworks.ro/account?workspace=ki910328#/organization)
=> fix: impersonate user with sales role

CHANGELOG.md, graphql/schema.graphql, node/resolvers/Mutations/CostCenters.ts, node/resolvers/Mutations/Organizations.test.ts, node/resolvers/Mutations/Organizations.ts, node/resolvers/Mutations/Settings.ts, node/resolvers/Mutations/Users.test.ts, node/resolvers/Mutations/Users.ts, node/resolvers/Queries/CostCenters.ts, node/resolvers/Queries/Settings.ts, node/resolvers/fieldResolvers.ts, node/resolvers/repository/CostCenterRepository.ts, node/typings.d.ts, node/utils/metrics/organization.test.ts, node/utils/metrics/organization.ts, node/utils/metrics/user.test.ts, node/utils/metrics/user.ts
We need to create a new endpoint to use in bulk import to create an organization and cost center with a specific ID.
- Call the CURL in the workspace
```CURL
curl --location 'https://createorg--b2bsuite.myvtex.com/_v/private/graphql/v1' \
--header 'Cookie: <YOUR_COOKIE>' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"mutation CreateOrganization($input: OrganizationInput!) {\n  createOrganizationAndCostCentersWithId(input: $input)\n    @context(provider: \"vtex.b2b-organizations-graphql\") {\n    id\n  }\n}","variables":{"input":{"id":"12345678","name":"Org Test 12345678","customFields":[],"defaultCostCenter":{"id":"12345678","name":"First","address":{"addressId":"0","addressType":"residential","city":"São Paulo","complement":null,"country":"BRA","receiverName":"princip …
```
=> feat: add to create an organization and cost center with a specified ID

CHANGELOG.md, node/resolvers/directives/checkAdminAccess.ts
When the API is called by Dandelion and Bulk-Import auth token isn't found.
- For Bulk-import
- Call the endpoint Upload file `/api/b2b/import/buyer-orgs?an={{accountName}}` and send the file
- Call the endpoint Start Import `api/b2b/import/buyer-orgs/`
[Workspace](https://createorg--b2bstoreqa.myvtex.com/admin)
We could use the cookie, but at the moment the bulk-import just works with the header `VtexIdclientAutCookie`.
=> feat: fallback to get an admin token on the header instead of a cookie

CHANGELOG.md, node/resolvers/Mutations/Organizations.test.ts, node/resolvers/Mutations/Organizations.ts
After requesting an organization creation, the admin user was without a cost center.
- Request an organization creation.
- Fill admin user
- Approve the organization.
[Workspace](https://tkt926539--b2bsuite.myvtex.com/)
=> fix: use cost center ID created on approve organization request

CHANGELOG.md, node/resolvers/Mutations/Organizations.ts
Fix the costCenterId when using mutation createOrganization
When using the createOrganization mutation, there is no costCenterId returned in the response:
- Access the graphQL IDE in [internal account](https://tkt928918--b2bsuite.myvtex.com/admin/graphql-ide)
- Create a organization using createOrganization mutation
- Before
-After
=> Fix the costCenterId

CHANGELOG.md, graphql/directives.graphql, graphql/schema.graphql, node/resolvers/directives.ts, node/resolvers/directives/auditAccess.ts, node/resolvers/directives/withPermissions.ts, node/utils/metrics/auth.ts, node/utils/metrics/user.ts
We need to monitor the access in the app, checking the graphql operations with authentication access.
- Access some audited operation from graphql.
getOrganizationById
getCostCenterById
getOrganizationByIdStorefront
getCostCenterByIdStorefront
getSalesChannels
getCostCentersByOrganizationId
getOrganizations
getOrganizationsByEmail
getB2BSettings
getMarketingTags
createOrganizationRequest
getBinding
getPaymentTerms
[Workspace](https://securitymetrics--b2bsuite.myvtex.com/)
=> feat: add audit metrics for authenticated access

CHANGELOG.md, node/resolvers/directives/auditAccess.ts
We are exceeding the limit of calls from the app to VBase. It is because we are using `checkPermission` to get the role and all permissions of the user, and this function calls any others that save data in VBase.
- Call the operation using the directive `@auditAccess`
[Workspace](https://securitymetrics--b2bsuite.myvtex.com/)
=> fix: remove get roles from metrics

CHANGELOG.md, graphql/schema.graphql, node/package.json, node/resolvers/Mutations/CostCenters.ts, node/typings.d.ts, node/yarn.lock
The existing `createCostCenter` graphql API does not allow creating a cost center with an user provided id. This PR allows that. This API still works without providing an ID, so the admin UI use case should not break.
This will allow us to create cost centers with user provided ids on the bulk import application.
1. Create a new cost center using the admin UI. It should work as before (and id will be automatically created for the cost center).
2. Call the `createCostCenter` graphql api providing the cost center id. It should also work if the id is not provided. The request looks like this:
```
curl --location 'https://b2bteam1399--b2bstoreqa.myvtex.com/_v/private/graphql/v1' \
--header 'Cookie: VtexIdclientAutCookie=<cookie>; janus_sid=1e52fe67-97ef-4793-9c3d-e6075f17a2e0' \
--header …
```
=> feat: allow create cost center with an user provided id

CHANGELOG.md, graphql/schema.graphql, node/resolvers/Mutations/Users.ts
Add a `createUserWithEmail` graphql with @checkAdminAccess directive to be called by the b2b-bulk-import app. This `createUserWithEmail` has stricter params than `addUser` and ultimately calls the storefront permissions addUser (just as the `addUser` graphql api).
This is also to avoid touching on the permissions of `addUser` that uses the @checkUserAccess directive.
Try to create an user calling the `createUserWithEmail` API providing the expected parameters (note only `canImpersonate` is optional):
```
createUser(
orgId: ID!
costId: ID!
roleId: ID!
name: String!
email: String!
canImpersonate: Boolean = false
)
```
=> feat: add createUserWithEmail graphql API

CHANGELOG.md, graphql/schema.graphql, node/clients/storefrontPermissions.ts, node/resolvers/Queries/MarketingTags.ts, node/resolvers/Routes/index.ts, node/resolvers/directives/checkUserAccess.ts
We found some apps that don't pass the token to call graphql queries or mutations. So we need a guarantee to have all integrations send the token, and we will block unauthenticated requests from the app provider.
- Open the [page organizations](https://b2bteam1285--b2bstore005.myvtex.com/admin/b2b-organizations/organizations#/organizations) in the admin. `test getOrganizations`
- Select [one organization](https://b2bteam1285--b2bstore005.myvtex.com/admin/b2b-organizations/organizations/d9e51195-0c39-11ed-835d-0ac601682b29/#/default) from page organizations. `test getOrganizationById`
- Open the [page My quotes](https://b2bteam1285--b2bstore005.myvtex.com/b2b-quotes). `test getOrganizationByIdStorefront and getOrganizationsByEmail`
- In the page My quotes, filter the quotes by cost center. …
=> feat: add token validation and token to call storefront-permission

CHANGELOG.md, node/clients/storefrontPermissions.ts
When it calls storefront-permission without a session token the axios http client throws an error because it doesn't accept undefined headers.
```
{"code":"ERR_HTTP_INVALID_HEADER_VALUE","name":"TypeError","message":"Invalid value \"undefined\" for header \"x-vtex-session\"","stack":"TypeError: Invalid value \"undefined\" for header \"x-vtex-session\"\n    at ClientRequest.setHeader (node:_http_outgoing:647:3)\n    at new ClientRequest (node:_http_client:284:14)\n    at Object.request (node:http:97:10)\n    at dispatchHttpRequest (/usr/local/data/service/node_modules/axios/lib/adapters/http.js:202:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/usr/local/data/service/node_modules/axios/lib/adapters/http.js:46:10)\n    at dispatchRequest …
```
=> fix: check the session token to set as header

CHANGELOG.md, node/utils/metrics/metrics.test.ts, node/utils/metrics/metrics.ts
We are currently seeing a lot of `Error to send metrics from auth metric` on opensearch logs with the following details:
```
...
"method":"post",
"timeout":0,
"url":"https://rc.vtex.com/api/analytics/schemaless-events"},
"request":{},
"isAxiosError":true,
"name":"Error",
"message":"Client network socket disconnected before secure TLS connection was established",
...
```
This PR adds retries to this post call to mitigate connection errors.
Change an organization detail on admin and check a metric for updating organization is sent
[Workspace](https://b2bteam1558--b2bstoreqa.myvtex.com/admin)
=> fix: add retry to sendMetric to avoid connection errors

CHANGELOG.md, graphql/schema.graphql, manifest.json, node/resolvers/directives/checkUserAccess.ts, node/service.json, policies.json
- We have an integration between storefront-permissions and b2b-organizations, and it is necessary to validate authentication in the request. But for some reason the storefront-permissions can't forward the cookie headers, and the token doesn't come in b2b-organization-graphql.
So, we change the integration structure and the graphql server intermediation to use the header `x-vtex-caller` as `vtex.storefront-permissions` and allow in b2b-organizations.
- Log in the b2b store
[Workspace](https://security--b2bsuite.myvtex.com/)
=> fix: allow storefront-permission call b2b-organizaiton-graphql when is enable to validate token

CHANGELOG.md, policies.json
When we deployed the previous version, the integration for other apps was broken. Rollback the configuration.
- Open the quotes page
- Create a new
- The success message is show.
[Workspace](https://security--b2bsuite.myvtex.com/)
=> fix: policies config rollback

CHANGELOG.md, node/resolvers/directives/checkUserAccess.ts
We added the token validation for `getOrganizationById` and `getCostCenterById`, but for some reason the app doesn't send the token header when called by the endpoint `/_v/private/b2b-checkout-settings/`.
- Add a product in cart
- Go to checkout 
[Workspace](https://security--b2bsuite.myvtex.com/)
=> fix: skip auth token validation for b2b-checkout-settings

CHANGELOG.md, node/resolvers/Queries/CostCenters.ts
When requesting the query getCostCenterById with an id that is not registered, the query is returning an error instead of empty result, as the getOrganizationById query does.
[Workspace](https://jamal--ewne.myvtex.com/admin/graphql-ide)
Current behavior:
Expected behavior (as this PR fixes):
Compared behavior with getOrganizationById:
=> Fix getCostCenterById error when not found

CHANGELOG.md, node/resolvers/directives/withPermissions.ts
The client can't add a user because the role isn't set correctly, just therefore, the storefront-permissions are returned by the app name sent to the sender in the extension persisted query.
Set the b2b-organizations app name on checkUserPermission to correctly get the user permissions.
[Workspace](https://orders.lyonbakery.com/account/?workspace=t1013317)
=> fix: set sender app as b2b-organizations on checkUserPermission

CHANGELOG.md, node/resolvers/directives/auditAccess.ts, node/resolvers/directives/checkAdminAccess.ts, node/resolvers/directives/checkUserAccess.ts, node/utils/metrics/auth.ts
Add metric to check access directives. With these metrics we can collect data about how these APIs are being used/called.
Data example collected from redshift:
`{"name":"b2b-suite-buyerorg-data","account":"b2bstoreqa","fields":{"caller":"vtex.graphql-server@1.67.8","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","forwardedHost":"testsec--b2bstoreqa.myvtex.com","hasAdminToken":true,"hasApiToken":false,"hasStoreToken":false,"operation":"getCostCenterByIdStorefront"},"kind":"b2b-organizations-graphql-auth-event","description":"CheckUserAccess"}`
=> chore: add metric to check access directives

CHANGELOG.md, node/clients/storefrontPermissions.ts
Provide app token on calls to storefront-permissions instead of admin/user tokens as these were already validated at this point.
=> fix: provide app token to storefront-permissions calls

CHANGELOG.md, graphql/schema.graphql, node/clients/sellers.ts, node/resolvers/Queries/Settings.ts, node/yarn.lock
The `getSellersPaginated` query now accepts a `paging` input parameter, allowing the client to specify the range of sellers to retrieve. The response includes a `paging` object with information about the total number of sellers and the range of sellers returned. This change improves the flexibility and efficiency of retrieving seller data.
```graphql
query GetSellersPaginated($page: Int, $pageSize: Int) {
getSellersPaginated(page: $page, pageSize: $pageSize) {
pagination {
page
pageSize
total
}
items {
id
name
email
}
}
}
```
=> feat: add paging support to getSellers query

CHANGELOG.md, graphql/schema.graphql
When I try to create an organization with cost centers, I cannot add the payments terms because the input typing has not been updated.
create an organization with cost centers by adding payments terms to the payload
[Workspace] https://jwp755--jwpepperdev.myvtex.com/
```
mutation {
createOrganizationAndCostCentersWithId(input: {name: "PaymentTerms3", tradeName: "PaymentTerms3", defaultCostCenter: {name: "PaymentTerms3", address: {addressId: "0", addressType: "", addressQuery: "", postalCode: "PaymentTerms3", country: "AFG", receiverName: "PaymentTerms3", city: "PaymentTerms3", state: "", street: "PaymentTerms3", number: "", neighborhood: "", geoCoordinates: [], reference: ""}, paymentTerms: [{id: "999999", name: "Credit card"}], phoneNumber: "1", businessDocument: "", stateRegistration: …
```
=> feat: add payment terms to default cost center input

CHANGELOG.md, graphql/schema.graphql, node/clients/LMClient.ts, node/resolvers/Queries/Settings.ts
There is a discrepancy between the name used in the product search and the name displayed in the B2B suite. The search uses the "trade name" registered in Account Management, while the B2B suite uses the "seller name" defined in Seller Management. This difference in naming can result in an inconsistent display of available products, since the search may not return products if the names registered in the two modules differ.
To resolve this issue and align the user experience, it was necessary to adjust the B2B suite to use the "trade name" from Account Management instead of the "seller name" from Seller Management. This will ensure that products are displayed correctly in the search and in the B2B suite interface, regardless of the name registered in Seller Management.
To achieve this, a …
=> feat: add getAccount query to retrieve account information

CHANGELOG.md, graphql/directives.graphql, graphql/schema.graphql, node/resolvers/directives.ts, node/resolvers/directives/validateStoreUserAccess.ts, node/utils/metrics/auth.ts
Add new store user token validation to getOrganizations and saveUser APIs. See more: https://vtex-dev.atlassian.net/browse/B2BTEAM-1891
=> fix: add new store token validation to some APIs

CHANGELOG.md, node/resolvers/Queries/CostCenters.ts, node/resolvers/Queries/Organizations.ts, node/resolvers/Queries/Users.ts, node/resolvers/Routes/index.ts
This fix adds the behavior of avoiding the call of the `checkUserPermission` API of `storefront-permissions` when session data is not available. 
This API uses session data to get the user permissions, so any call without such data would result in an error in `storefront-permissions` (and consequently another one in `b2b-organizations-graphql`) and a `null` result. For this reason, it is not an issue to assume beforehand that the API call will return `null` when the session data is already empty.
Therefore, by avoiding this call when the session data is already known to be empty, the errors won't happen and an unnecessary call between apps will be prevented. The goal is to reduce the amount of error logs in both apps. More details on …
=> fix: check user permission error

CHANGELOG.md, graphql/schema.graphql, node/package.json, node/resolvers/Queries/Organizations.ts, node/typings.d.ts, node/yarn.lock
Inactive organizations shown when changing organizations
- Register at least two organizations with the same email;
- Inactivate an organization;
- Enter the store and change the organization; the inactive organization can't be shown in the list.
[Workspace](https://giurigaud--b2bstore005.myvtex.com/)
Before change:
After change:
=> fix: [KI 1092989] getOrganizationsByEmail to return only active organizations

CHANGELOG.md, graphql/schema.graphql, node/resolvers/Mutations/Settings.ts, node/typings.d.ts
This change allows customization of the top bar appearance (name and color) in B2B settings.
Get:
```
{
getB2BSettings {
uiSettings {
showModal
clearCart
topBar {
name
hexColor
}
}
}
}
```
Insert:
```
mutation {
saveB2BSettings(
input: {
uiSettings: {
showModal: true
clearCart: false
topBar: {
name: "Top Bar Example"
hexColor: "#FF5733"
}
}
}
) {
status
}
}
```
https://guidobernal--b2bstore005.myvtex.com/admin/graphql-ide
As it's just a type addition, there is no concrete usage example. Testing can be done through schema verification.
No alternatives.
:)
=> feat: add topBar settings type

CHANGELOG.md, node/resolvers/Mutations/Organizations.ts
There is no mail notification to `createOrganizationAndCostCenterWithAdminUser` mutation
It was added to that to keep the same behavior as others.
https://mail1--b2bstoreqa.myvtex.com/
=> Mail notification to createOrganizationAndCostCenterWithAdminUser Mutation

CHANGELOG.md, node/resolvers/Mutations/Users.ts
Empty return when using the mutation `removeUsersWithEmail`
[Workspace](https://deleteuser--b2bstore005.myvtex.com/admin)
Before
After
=> Fix return removeUserWithEmail

CHANGELOG.md, node/resolvers/directives/withPermissions.ts
It was hardcoded the sender to storefront-permissions the sender.
So it was fixed to send that correctly to SFP.
https://beta.rahrbsg.com/account?workspace=arturu#/organization
Ticket:
https://vtexhelp.zendesk.com/agent/tickets/1182757
[Workspace](Link goes here!)
=> [Zend Desk] Unable to add users on production.

CHANGELOG.md, node/resolvers/Mutations/Organizations.ts
Adding `notes` when updating organization requests
Create a organization request, and check the notes after, it'll be "Auto approved"
[Workspace](https://tkt1197323--b2bstore005.myvtex.com/organization-request)
=> Added `notes` when updating organization requests

catalog-info.yaml
This PR updates the owner of b2b-organizations-graphql to te-0010 in the catalog-info.yaml file.
This is necessary because now in DK Portal we will define the team -> component relationship through the team id instead of the owner name.
=> Update owner of b2b-organizations-graphql to te-0010

node/resolvers/Mutations/Settings.ts
The "saveB2BSettings" mutation first save the current configurations object to use it as a fallback for parameters that are not sent in the mutation to ensure compatibility.
In cases where "currentB2BSettings.uiSettings: null" an error is thrown due to not being able to read "currentB2BSettings.uiSettings.showModal". An example is when trying to create a new custom field.
This fix sets the field "currentB2BSettings.uiSettings" as optional and, for cases where it is "null", no reading error is thrown.
In a B2B Store where the configurations for "uiSettings: null" try to create a new CustomField. 
[Workspace](https://savesettings--b2bstore005.myvtex.com/admin/b2b-organizations/organizations#/custom-fields)
After the fix when using the mutation "saveB2BSettings" in for a store where …
=> Set parameters in saveB2BSettings mutation as optional

CHANGELOG.md
As version 1.0.0 already existed and was deprecated, we need to generate a new patch version.
This is an empty commit just to generate version 1.0.1
=> fix: update patch version

CHANGELOG.md, graphql/schema.graphql
`getOrganizationRequestById` requests were failing with `No auth cookie provided`.
This is because the cache control for this API was set to `PUBLIC`.
This PR changes the cache control for this API to `PRIVATE`. It also fixes the same thing for the `getCostCenters` APIs (that are less used, but would suffer from the same issue).
=> fix: allow GetOrganizationRequestById to receive cookies
